name: .NET 6.0

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish 64-bit
      run: dotnet publish --configuration Release --no-self-contained --runtime win-x64 --output ./published_app/Release64
  
    - name: Publish 32-bit
      run: dotnet publish --configuration Release --no-self-contained --runtime win-x86 --output ./published_app/Release86

    - name: Publish ARM64
      run: dotnet publish --configuration Release --no-self-contained --runtime win-arm64 --output ./published_app/ReleaseARM64

    - name: Upload 64-bit artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-application-64 
        path: |
          ./published_app/Release64/*
    
    - name: Upload 32-bit artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-application-32
        path: |
          ./published_app/Release86/*

    - name: Upload ARM64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-application-ARM64
        path: |
          ./published_app/ReleaseARM64/*
